[package]
name = "mysocial-graphql-client-build"
version = "0.1.0"
authors = ["Brandon Williams <brandon@socialproof.foundation>"]
repository = "https://github.com/The-Social-Proof-Foundation/mysocial-core"
license = "Apache-2.0"
edition = "2021"

[dependencies]
cynic-codegen = "3.8.0"

